### ISSUE TITLE
UCI and (K)nps

### ISSUE THREAD

**Issue by Matthies** [ChrisWhittington/Chess-System-Tal-NNUE-2#1]
`info depth 21 seldepth 32 time 727 nodes 744804 score cp 37 lowerbound pv d2d4 d7d5 g1f3 hashfull 11 Knps 1024489`
Knps is not mentioned in UCI specs, only nps. And IF the K stands for kilo, it is probably even wrong.
GUIs may be gracious with it, at least Arena seems to display correct speed.

**Comment by ChrisWhittington** [comment]
thanks for that one. I was dividing by a factor of 1000 (correctly because time is in ms), but obviously later thought this was a Knps conversion and put the K in. I guess.


    On Thursday, 29 June 2023 at 18:41:33 CEST, Andreas Matthies ***@***.***> wrote:  
 
 


info depth 21 seldepth 32 time 727 nodes 744804 score cp 37 lowerbound pv d2d4 d7d5 g1f3 hashfull 11 Knps 1024489
Knps is not mentioned in UCI specs, only nps. And IF the K stands for kilo, it is probably even wrong.
GUIs may be gracious with it, at least Arena seems to display correct speed.

**Comment by ChrisWhittington** [comment]
Fixed for next build
